AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Handler: index.handler
      Runtime: nodejs8.10
Outputs:
  Function:
    Description: The logical id of the function defined in this template
    Value: !Ref Function
  FunctionArn:
    Description: The arn of the function defined in this template
    Value: !GetAtt Function.Arn